#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stappen%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Jij bedient de browser; deze wizard zegt precies wat je moet doen en\n' "$DIM"
  printf '  vangt de waarden op die je terugkopieert. Stoppen mag altijd met Ctrl-C:\n'
  printf '  bij een herstart onthoudt hij wat al opgeslagen is.%s\n' "$RESET"
  pause "Klaar om te starten?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stap %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Druk op Enter om verder te gaan}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [j/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[JjYy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter behoudt de huidige]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter behoudt de huidige]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ geschreven%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ gezet%s GitHub-secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub-secret $name (zet hem handmatig: gh secret set $name)")
  warn "GitHub-secret $name overgeslagen: gh niet klaar; zet hem later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ gezet%s GitHub-variabele %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub-variabele $name")
  warn "GitHub-variabele $name overgeslagen, gh niet klaar; zet hem later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Klaar%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "${#WRITTEN_ENV[@]} waarde(n) naar $ENV_FILE geschreven: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "${#WRITTEN_SECRET[@]} GitHub-secret(s) gezet: ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "nog handmatig te doen:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
ENV_FILE="$PROJECT_ROOT/.env"

DOMAIN="prestige-automotive.be"

# run_deploy geeft de ingevulde FTP-waarden als environment variables door aan
# het PowerShell-script, zodat ze nergens in een bestand terechtkomen.
run_deploy() {
  COMBELL_FTP_HOST="$COMBELL_FTP_HOST" \
  COMBELL_FTP_USER="$COMBELL_FTP_USER" \
  COMBELL_FTP_PASS="$COMBELL_FTP_PASS" \
  COMBELL_FTP_ROOT="$COMBELL_FTP_ROOT" \
  powershell.exe -NoProfile -ExecutionPolicy Bypass \
    -File "$(cygpath -w "$PROJECT_ROOT/deploy/deploy-combell.ps1")" "$@"
}

# current_ip toont waar het domein op dit moment naartoe wijst.
current_ip() {
  if command -v nslookup >/dev/null 2>&1; then
    nslookup "$DOMAIN" 8.8.8.8 2>/dev/null | awk '/^Address/{last=$NF} END{print last}'
  fi
}

banner "Prestige Automotive → Combell"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Hostingpakket controleren"
say "Eerste vraag: heb je echt webhosting bij Combell, of enkel het domein?"
say "De domeinnaam prestige-automotive.be bezitten is niet hetzelfde als"
say "hosting hebben — dat is een apart product, en zonder hosting werkt niets"
say "van wat hierna komt."
open_url "https://my.combell.com"
step "Log in en ga naar 'My products' → 'Web hosting'."
note "Tip: de taalkeuze (NL / FR / EN) staat rechtsonderaan de pagina."
say ""
step "Je zou nu een hostingpakket in de lijst moeten zien. Controleer twee dingen:"
step "  a) er staat Linux bij (niet Windows)"
step "  b) het pakket is actief, niet vervallen"
say ""
warn "Lege lijst? Stop hier. Bestel eerst Linux-webhosting en start deze wizard"
warn "daarna opnieuw. Alles hieronder gaat ervan uit dat het pakket bestaat."
say ""
if ! confirm "Heb je een actief LINUX-hostingpakket?"; then
  say ""
  warn "Gestopt. Bestel Linux-webhosting bij Combell en start de wizard opnieuw."
  exit 0
fi
step "Open het pakket. Onder 'Overview' staat 'IP address (v4)'."
note "Voor dit account is dat 188.208.37.139 (pakket Webhosting Business,"
note "geregistreerd op prestige-garage.be). Druk op Enter om die over te nemen."
ask COMBELL_HOST_IP "IP-adres van de hosting [188.208.37.139]:"
[[ -z "$COMBELL_HOST_IP" ]] && COMBELL_HOST_IP="188.208.37.139"
write_env COMBELL_HOST_IP "$COMBELL_HOST_IP"
note "Dit heb je in stap 8 nodig, bij de DNS-omschakeling."
pause

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Domein toevoegen aan het pakket"
say "Het hostingpakket staat op prestige-garage.be, niet op het domein dat we"
say "deployen. Er passen 4 websites op het pakket en er is er 1 in gebruik, dus"
say "prestige-automotive.be moet er nog bij."
say ""
warn "Deze stap bepaalt WAAR je bestanden heen moeten. Sla je hem over, dan"
warn "upload je straks 54 bestanden in een map die niemand serveert."
say ""
open_url "https://my.combell.com"
note "Let op: de lijst onder 'Web hosting' toont PAKKETTEN, geen websites. Er"
note "staat één rij (prestige-garage.be) omdat je één pakket hebt, genoemd naar"
note "het domein waarop het is aangemaakt. Dat blijft zo, ook na deze stap."
step "Dashboard → Web hosting → 'Manage hosting' → 'Websites & SSL'."
step "Klik '+ Add website' rechtsboven en voeg $DOMAIN toe."
say ""
note "Resultaat: Combell zet hem erbij als 'Subsite' met als documentroot"
note "  /subsites/$DOMAIN"
note "Dus NIET /www — dat is de map van prestige-garage.be."
say ""
note "Onder de website staan twee rijen: $DOMAIN en www.$DOMAIN. De bleke"
note "schakelaar betekent NIET 'uit' — beide domeinen worden beantwoord."
note "Je hoeft daar niets te wijzigen."
say ""
warn "BELANGRIJK — Combell maakt bij het toevoegen automatisch een AAAA-record"
warn "aan, met het IPv6-adres van deze website. Dat werkt meteen: bezoekers met"
warn "IPv6 (veel mobiele netwerken) komen dan al op de lege Combell-map terecht,"
warn "terwijl IPv4-bezoekers nog de oude site zien. Half kapot dus."
say ""
step "Ga nu naar Dashboard → 'DNS & forwarding management' → $DOMAIN →"
step "'AAAA-records' en VERWIJDER dat record. In stap 8 zet je het terug,"
step "samen met het A-record."
step "Controleren:  nslookup -type=AAAA $DOMAIN 8.8.8.8"
say ""
note "De rode slotjes betekenen enkel 'nog geen SSL-certificaat'. Dat klopt:"
note "dat komt pas in stap 9."
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "FTP-gegevens"
say "Het deploy-script uploadt via FTPS. Server en gebruikersnaam zijn bekend;"
say "het wachtwoord moet je zelf ophalen of instellen."
open_url "https://my.combell.com"
step "My products → Web hosting → prestige-garage.be → 'FTP & SSH'."
step "Ken je het wachtwoord niet, zoek dan de optie om het te wijzigen en"
step "stel een nieuw wachtwoord in. Kopieer het meteen."
say ""
note "Server en gebruikersnaam staan in het venster 'Login details'."
note "Druk op Enter om de bekende waarden over te nemen."
ask COMBELL_FTP_HOST "FTP-server [ftp.prestige-garagebe.webhosting.be]:"
[[ -z "$COMBELL_FTP_HOST" ]] && COMBELL_FTP_HOST="ftp.prestige-garagebe.webhosting.be"
say ""
warn "De gebruikersnaam is GEEN domeinnaam. Het is prestige-garagebe@prestige-garagebe."
ask COMBELL_FTP_USER "FTP-gebruikersnaam [prestige-garagebe@prestige-garagebe]:"
[[ -z "$COMBELL_FTP_USER" ]] && COMBELL_FTP_USER="prestige-garagebe@prestige-garagebe"
ask_secret COMBELL_FTP_PASS "FTP-wachtwoord (wordt niet getoond):"
say ""
step "En de documentroot uit de vorige stap."
ask COMBELL_FTP_ROOT "Webroot [/subsites/$DOMAIN]:"
[[ -z "$COMBELL_FTP_ROOT" ]] && COMBELL_FTP_ROOT="/subsites/$DOMAIN"
write_env COMBELL_FTP_HOST "$COMBELL_FTP_HOST"
write_env COMBELL_FTP_USER "$COMBELL_FTP_USER"
write_env COMBELL_FTP_PASS "$COMBELL_FTP_PASS"
write_env COMBELL_FTP_ROOT "$COMBELL_FTP_ROOT"
warn "In .env staat nu je FTP-wachtwoord. Het bestand staat in .gitignore —"
warn "commit of deel het nooit."
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "PHP-versie (waarschijnlijk al goed)"
say "Het contactformulier is PHP en heeft 8.1 of nieuwer nodig."
say ""
note "Op dit pakket stond PHP al op 8.3 — dan hoef je hier niets te doen."
say ""
step "Wil je het nakijken: Web hosting → prestige-garage.be → 'PHP settings'."
step "Bovenaan staat 'Version: PHP 8.3'."
note "De cURL-extensie staat standaard aan bij Combell."
pause "Klaar? Druk op Enter."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Contactformulier: Resend"
say "Het formulier verstuurt mail via Resend. Je hebt een API-sleutel nodig, en"
say "het domein moet daar geverifieerd zijn, anders belandt de mail in spam."
say ""
step "1. Maak een gratis account op resend.com (3.000 mails per maand)."
step "2. Domains → Add domain → $DOMAIN."
step "3. Resend toont 'Fill in your DNS Records'. Voor dit domein zijn dat:"
step "     TXT    resend._domainkey   p=MIGfMA...wIDAQAB   (DKIM)"
step "     CNAME  rsend               rsend-ap....mta.net"
step "     CNAME  send                send.for....mta.net"
step "   Scroll de hele pagina door — er kan nog een DMARC-record onder staan."
step "4. Voeg ze toe bij Combell: Dashboard → 'DNS & forwarding management' →"
step "   $DOMAIN. Er is een aparte pagina per type: 'TXT-records' en"
step "   'CNAME-records'."
step "5. Wacht tot Resend het domein als Verified toont."
step "6. API Keys → Create → rechten 'Sending access' → kopieer de sleutel."
say ""
warn "Het MX-record van $DOMAIN wijst naar smtp.google.com en moet exact"
warn "zo blijven — daar loopt de bedrijfsmail over."
note "Vraagt Resend een MX-record op een SUBdomein (bv. send.$DOMAIN)? Dat is"
note "een ander record en mag je wel toevoegen; het raakt de mail op het"
note "hoofddomein niet."
open_url "https://resend.com/domains"
pause "Domein geverifieerd en sleutel gekopieerd? Druk op Enter."
say ""
ask_secret RESEND_API_KEY "Plak de Resend API-sleutel (wordt niet getoond):"
ask CONTACT_TO "Waar moeten de aanvragen naartoe? [Geoffrey@$DOMAIN]:"
[[ -z "$CONTACT_TO" ]] && CONTACT_TO="Geoffrey@$DOMAIN"
ask CONTACT_FROM "Afzenderadres [website@$DOMAIN]:"
[[ -z "$CONTACT_FROM" ]] && CONTACT_FROM="website@$DOMAIN"
write_env RESEND_API_KEY "$RESEND_API_KEY"
write_env CONTACT_TO "$CONTACT_TO"
write_env CONTACT_FROM "$CONTACT_FROM"

cat > "$PROJECT_ROOT/prestige-config.php" <<PHPCFG
<?php
/* Gegenereerd door deploy/setup-combell.sh — niet committen. */
return [
    'RESEND_API_KEY' => '$RESEND_API_KEY',
    'CONTACT_TO'     => '$CONTACT_TO',
    'CONTACT_FROM'   => 'Prestige Automotive <$CONTACT_FROM>',
];
PHPCFG
printf '  %s✓ geschreven%s prestige-config.php\n' "$GREEN" "$RESET"
note "Dit bestand komt één map BOVEN de webroot, zodat geen enkele URL erbij kan."
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "De site uploaden"
say "Niets van wat je hier doet is al zichtbaar voor het publiek: het domein"
say "wijst nog naar de oude Squarespace-site. We vullen enkel de Combell-server."
say ""
step "Eerst een dry run, zodat je ziet wat er verstuurd zou worden."
pause "Druk op Enter om hem te draaien."
run_deploy -DryRun || true
say ""
if ! confirm "Ziet die lijst er goed uit (ongeveer 54 bestanden)?"; then
  warn "Gestopt, zodat je het kunt nakijken. Start de wizard opnieuw als je klaar bent."
  exit 0
fi
say ""
step "Nu de echte upload. De eerste keer duurt dit enkele minuten."
run_deploy -ConfigFile "$(cygpath -w "$PROJECT_ROOT/prestige-config.php")"
pause

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Testen VOOR je aan de DNS komt"
say "Dit is de stap die voorkomt dat je de live site sloopt. Je bekijkt de"
say "Combell-versie op je eigen computer, terwijl de rest van de wereld nog"
say "gewoon Squarespace ziet."
say ""
step "Open Kladblok ALS ADMINISTRATOR (rechtsklik → Als administrator uitvoeren)."
step "Open dit bestand:  C:\\Windows\\System32\\drivers\\etc\\hosts"
step "Zet onderaan deze regel bij, en sla op:"
say ""
printf '      %s%s %s%s\n' "$BOLD" "$COMBELL_HOST_IP" "$DOMAIN" "$RESET"
say ""
step "Surf nu naar http://$DOMAIN. Je kijkt naar Combell."
note "Biedt het Combell-paneel een eigen tijdelijke URL aan, gebruik die dan."
say ""
step "Controleer op die voorvertoning:"
step "  - de homepage laadt, met logo en foto's"
step "  - /prijzen.html en /galerij.html zien er goed uit"
step "  - /contact.html: verstuur een testbericht en kijk of het aankomt"
step "    op $CONTACT_TO"
say ""
warn "Als je klaar bent met testen: HAAL die regel weer uit het hosts-bestand,"
warn "anders blijft enkel jouw computer later het verkeerde zien."
say ""
if ! confirm "Werkte alles, inclusief het contactformulier?"; then
  say ""
  warn "Schakel de DNS nog niet om. Los eerst op wat stuk is."
  note "Formulier zegt 'E-mail is niet geconfigureerd.' → prestige-config.php"
  note "  ontbreekt of staat verkeerd; draai stap 5 opnieuw."
  note "Formulier geeft 404 → mod_rewrite; zie docs/COMBELL-DEPLOY.md,"
  note "  hoofdstuk Troubleshooting."
  note "Start deze wizard opnieuw zodra het opgelost is."
  exit 0
fi
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "DNS omschakelen"
say "Dit is het moment waarop de publieke site van Squarespace naar Combell gaat."
say ""
note "Nu wijst $DOMAIN naar: $(current_ip)  (Squarespace)"
note "Het moet wijzen naar:  $COMBELL_HOST_IP  (Combell)"
say ""
warn "WIJZIG ENKEL DE A-RECORDS."
warn "Blijf van de MX-records af. Die wijzen naar Google (smtp.google.com)."
warn "Verwijder of wijzig je die, dan komt er geen bedrijfsmail meer binnen."
say ""
open_url "https://my.combell.com"
step "Dashboard → 'DNS & forwarding management' → $DOMAIN."
step "In het linkermenu staat een aparte pagina per recordtype. Klik op"
step "'A-records'. MX-records staan op een eigen pagina — blijf daarvan af."
step "Je ziet vier A-records, allemaal van Squarespace:"
step "    198.185.159.144  198.185.159.145  198.49.23.144  198.49.23.145"
step "Vervang ze door ÉÉN record:"
printf '      %s%s  →  %s%s\n' "$BOLD" "$DOMAIN" "$COMBELL_HOST_IP" "$RESET"
step "Heeft 'www' een eigen A-record, pas dat dan ook aan. Is het een CNAME"
step "naar het domein, laat het dan staan — dat volgt vanzelf."
step "Opslaan."
say ""
note "De wijziging is meestal binnen enkele minuten actief, soms pas na uren."
say ""
if ! confirm "Heb je de A-records gewijzigd en de MX-records met rust gelaten?"; then
  warn "Tot dat gebeurd is valt er niets meer te doen. Start de wizard daarna opnieuw."
  exit 0
fi
pause

# ── 9 ───────────────────────────────────────────────────────────────────
stage "SSL-certificaat"
say "Nu de DNS naar Combell wijst, kan Let's Encrypt het domein controleren en"
say "een gratis certificaat uitreiken. Eerder kon dat niet."
say ""
note "$DOMAIN wijst op dit moment naar: $(current_ip)"
note "Wacht tot daar $COMBELL_HOST_IP staat voor je verdergaat."
say ""
open_url "https://my.combell.com"
step "My products → Web hosting → jouw pakket → zoek SSL / certificaten."
step "Zet het gratis Let's Encrypt-certificaat aan voor $DOMAIN en www.$DOMAIN."
step "Wacht tot het als actief wordt gemeld — meestal enkele minuten."
say ""
step "Controleer daarna of https://$DOMAIN laadt met een slotje en zonder waarschuwing."
say ""
if ! confirm "Werkt https://$DOMAIN met een geldig certificaat?"; then
  warn "Ga niet verder: de volgende stap stuurt al het verkeer naar HTTPS, en"
  warn "zonder certificaat is de site dan onbereikbaar."
  note "Start deze wizard opnieuw zodra het certificaat actief is."
  exit 0
fi
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "HTTPS afdwingen, en afronden"
say "Laatste stap: de redirect aanzetten die http://-bezoekers naar https://"
say "stuurt. Die stond tot nu toe bewust uit."
say ""
if grep -q '^  #RewriteCond %{HTTPS} !=on' .htaccess; then
  sed -i '/@HTTPS-REDIRECT-START/,/@HTTPS-REDIRECT-END/ s/^  #Rewrite/  Rewrite/' .htaccess
  printf '  %s✓ aangezet%s de HTTPS-redirect in .htaccess\n' "$GREEN" "$RESET"
else
  note "Stond al aan — niets te wijzigen."
fi
say ""
step "Enkel dat ene bestand gaat opnieuw omhoog."
run_deploy -Only ".htaccess"
say ""
step "Laatste controles, in een privé-/incognitovenster:"
step "  - http://$DOMAIN  springt door naar https://"
step "  - https://www.$DOMAIN werkt ook"
step "  - /te-koop.html toont de auto's uit Firestore"
step "  - het contactformulier verstuurt nog steeds"
say ""
warn "Is /te-koop.html leeg? Open de Firebase-console →"
warn "Authentication → Settings → Authorized domains, en voeg $DOMAIN toe."
say ""
warn "En: haal de regel weg die je in stap 6 aan"
warn "C:\\Windows\\System32\\drivers\\etc\\hosts hebt toegevoegd."
say ""
note "De oude Squarespace-site is niet meer bereikbaar op dit domein, maar het"
note "abonnement blijft doorlopen tot je het bij Squarespace zelf opzegt."
pause

finish
say "Voor een volgende wijziging heb je deze wizard niet meer nodig."
say "Zet de drie COMBELL_FTP_*-variabelen en draai:"
say ""
say "    .\\deploy\\deploy-combell.ps1"
say ""
say "Volledige uitleg: docs/COMBELL-DEPLOY.md"
say ""
